ServerName localhost
ProxyPreserveHost On
ProxyPass /api/ http://api:8000/api/
ProxyPassReverse /api/ http://api:8000/api/
ProxyPass /health http://api:8000/health
ProxyPassReverse /health http://api:8000/health
